# Generated by Django 5.2.7 on 2025-11-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(default='sensors', max_length=50)),
                ('thingspeak_channel', models.IntegerField(unique=True)),
                ('mqtt_topic', models.CharField(blank=True, max_length=200, null=True)),
                ('ultimo_dato', models.DateTimeField(blank=True, null=True)),
                ('valor_actual', models.FloatField(blank=True, null=True)),
                ('unidad', models.CharField(default='°C', max_length=20)),
                ('estado', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Advertencia')], default='offline', max_length=10)),
                ('umbral_alerta', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dispositivo IoT',
                'verbose_name_plural': 'Dispositivos IoT',
            },
        ),
    ]
