# Generated by Django 5.2.7 on 2025-11-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_0', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositivo',
            options={'verbose_name': 'Dispositivo ESP32', 'verbose_name_plural': 'Dispositivos ESP32'},
        ),
        migrations.RenameField(
            model_name='dispositivo',
            old_name='umbral_alerta',
            new_name='valor1',
        ),
        migrations.RenameField(
            model_name='dispositivo',
            old_name='valor_actual',
            new_name='valor2',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='unidad',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='label1',
            field=models.CharField(blank=True, default='Field 1', max_length=30),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='label2',
            field=models.CharField(blank=True, default='Field 2', max_length=30),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='label3',
            field=models.CharField(blank=True, default='Field 3', max_length=30),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='label4',
            field=models.CharField(blank=True, default='Field 4', max_length=30),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='label5',
            field=models.CharField(blank=True, default='Field 5', max_length=30),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='label6',
            field=models.CharField(blank=True, default='Field 6', max_length=30),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='label7',
            field=models.CharField(blank=True, default='Field 7', max_length=30),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='label8',
            field=models.CharField(blank=True, default='Field 8', max_length=30),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='unidad1',
            field=models.CharField(blank=True, default='°C', max_length=10),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='unidad2',
            field=models.CharField(blank=True, default='%', max_length=10),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='unidad3',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='unidad4',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='unidad5',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='unidad6',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='unidad7',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='unidad8',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='valor3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='valor4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='valor5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='valor6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='valor7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='valor8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='icono',
            field=models.CharField(default='microchip', max_length=50),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='thingspeak_channel',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
